### ISSUE TITLE
Can we integrate this framework with VUE JS.

### ISSUE THREAD

**Issue by dimer22zhc** [felixdorn/flash#2]
I love this framework. Very good job. And how can we help you ?

**Comment by felixdorn** [comment]
I don't really understand how you want do to that, i mean, VueJS is made for front-end and this library made for back-end, i never really used Vue but if you can add global function you can make something like that https://gist.github.com/felixdorn/c192d3b21a0ccc41d230655bd5def0e4

**Comment by felixdorn** [comment]
In future version i'll add support for twig and maybe VueJS if you explain more clearly what's your problem.
